### ISSUE TITLE
Autoscrolling on zoomed in text

### ISSUE THREAD

**Issue by Oreolek** [erkyrath/lectrote#52] opened 2016-04-18 05:35 UTC
The autoscroll is buggy when the game is zoomed in (zoom > 1).

**Comment by erkyrath** [comment] 2016-04-18 16:17
Buggy how?

Are you using the latest release?

**Comment by Oreolek** [comment] 2016-04-18 16:27
Quixe version 2.1.2; Electron version 0.37.6 (Node 5.10.0, Chrome 49.0.2623.75), the latest git commit, Ubuntu Linux 15.10.

Here's [a video](https://oreolek.ru/temp/lectrote.webm) of "Foo Foo" game, margins 15%, zoom x3. I'm trying scroll wheel and Page Up/Down buttons.

**Comment by erkyrath** [comment] 2016-04-18 17:33
Right, you gotta get up to Quixe 2.1.4. That's when that bug was fixed.

**Comment by erkyrath** [comment] 2016-04-18 17:40
Duplicate of https://github.com/erkyrath/lectrote/issues/29 , https://github.com/erkyrath/quixe/issues/10

**Closed by erkyrath** 2016-04-18 17:40 UTC
